services:
  front-react:
    build:
      context: ./client
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - '5000:5000'

  server-dev:
    build:
      context: ./server
    environment:
      - NODE_ENV=development
      - SH_SERVER_HOST=${SH_SERVER_HOST}
      - SH_SERVER_PORT=${SH_SERVER_PORT}
      - WAIT_HOSTS=db-dev:5432,mongo-dev:27017
      - WAIT_HOSTS_TIMEOUT=30
    ports:
      - '3000:3000'
    depends_on:
      - postgres_dev
      - mongo_dev
    volumes:
      - ./var/www/html/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules

  mongo_dev:
    image: mongo:7.0.14
    ports:
      - '12345:27017'

  postgres_dev:
    image: postgres:16.4-bullseye
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - '12346:5432'
