### Get all contests (without filters, default pagination)
GET http://localhost:3000/api/contest/getAllContests HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6IkNyZWF0b3IiLCJsYXN0TmFtZSI6IlRlc3QiLCJkaXNwbGF5TmFtZSI6IkNyZWF0b3JUZXN0IiwiZW1haWwiOiJjcmVhdG9yQGdtYWlsLmNvbSIsInJvbGUiOiJjcmVhdG9yIiwiYXZhdGFyIjoiYW5vbi5wbmciLCJiYWxhbmNlIjoiMCIsInJhdGluZyI6MCwiaWF0IjoxNzI2MDU2MTk3LCJleHAiOjE3MjYwNTk3OTd9._uWWf6EIVgAVnGEFHtqTKyBYZ_T2-pV6QJ1WHMNeu9k

### Get all contests (with filters by industry and awardSort, pagination applied)
GET http://localhost:3000/api/contest/getAllContests?typeIndex=1&industry=Health&awardSort=desc&limit=10&offset=0&ownEntries=false
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6IkNyZWF0b3IiLCJsYXN0TmFtZSI6IlRlc3QiLCJkaXNwbGF5TmFtZSI6IkNyZWF0b3JUZXN0IiwiZW1haWwiOiJjcmVhdG9yQGdtYWlsLmNvbSIsInJvbGUiOiJjcmVhdG9yIiwiYXZhdGFyIjoiYW5vbi5wbmciLCJiYWxhbmNlIjoiMCIsInJhdGluZyI6MCwiaWF0IjoxNzI2MDU2MTk3LCJleHAiOjE3MjYwNTk3OTd9._uWWf6EIVgAVnGEFHtqTKyBYZ_T2-pV6QJ1WHMNeu9k

### Get all contests (only user’s own entries)
GET http://localhost:3000/api/contest/getAllContests?ownEntries=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6IkNyZWF0b3IiLCJsYXN0TmFtZSI6IlRlc3QiLCJkaXNwbGF5TmFtZSI6IkNyZWF0b3JUZXN0IiwiZW1haWwiOiJjcmVhdG9yQGdtYWlsLmNvbSIsInJvbGUiOiJjcmVhdG9yIiwiYXZhdGFyIjoiYW5vbi5wbmciLCJiYWxhbmNlIjoiMCIsInJhdGluZyI6MCwiaWF0IjoxNzI2MDQ5OTIxLCJleHAiOjE3MjYwNTM1MjF9.Nm6AYFUapoWQ3-NaVZuZ1YKfKiJmdjYYbS92qTpVZ60

// =============================================

### Get contest by ID
GET http://localhost:3000/api/contest/getContestById/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6IkNyZWF0b3IiLCJsYXN0TmFtZSI6IlRlc3QiLCJkaXNwbGF5TmFtZSI6IkNyZWF0b3JUZXN0IiwiZW1haWwiOiJjcmVhdG9yQGdtYWlsLmNvbSIsInJvbGUiOiJjcmVhdG9yIiwiYXZhdGFyIjoiYW5vbi5wbmciLCJiYWxhbmNlIjoiMCIsInJhdGluZyI6MCwiaWF0IjoxNzI2MDQ5OTIxLCJleHAiOjE3MjYwNTM1MjF9.Nm6AYFUapoWQ3-NaVZuZ1YKfKiJmdjYYbS92qTpVZ60

// =============================================

### Get customers contests
GET http://localhost:3000/api/contest/getCustomersContests?status=active&limit=10&offset=0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkN1c3RvbWVyIiwibGFzdE5hbWUiOiJUZXN0IiwiZGlzcGxheU5hbWUiOiJDdXN0b21lclRlc3QiLCJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImF2YXRhciI6ImFub24ucG5nIiwiYmFsYW5jZSI6IjAiLCJyYXRpbmciOjAsImlhdCI6MTcyNjA1MDA1MiwiZXhwIjoxNzI2MDUzNjUyfQ.Nfoic9c26oUxsy-ifYCOHHXiH-bXN41B4nFvEq5-R-U

// =============================================

### Update Contest without file
PATCH http://localhost:3000/api/contest/updateContest/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkN1c3RvbWVyIiwibGFzdE5hbWUiOiJUZXN0IiwiZGlzcGxheU5hbWUiOiJDdXN0b21lclRlc3QiLCJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImF2YXRhciI6ImFub24ucG5nIiwiYmFsYW5jZSI6IjAiLCJyYXRpbmciOjAsImlhdCI6MTcyNjA1MDA1MiwiZXhwIjoxNzI2MDUzNjUyfQ.Nfoic9c26oUxsy-ifYCOHHXiH-bXN41B4nFvEq5-R-U

{
  "title": "Patched Contest Title",
  "industry": "Health",
  "focusOfWork": "New focus for the contest",
  "targetCustomer": "Health-conscious individuals",
  "status": "active",
  "prize": "100"
}

// =============================================

### Get data for contest (example: typeOfName & nameStyle)
GET http://localhost:3000/api/contest/getDataForContest?characteristic1=typeOfName&characteristic2=nameStyle HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkN1c3RvbWVyIiwibGFzdE5hbWUiOiJUZXN0IiwiZGlzcGxheU5hbWUiOiJDdXN0b21lclRlc3QiLCJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImF2YXRhciI6ImFub24ucG5nIiwiYmFsYW5jZSI6IjAiLCJyYXRpbmciOjAsImlhdCI6MTcyNjA1MDA1MiwiZXhwIjoxNzI2MDUzNjUyfQ.Nfoic9c26oUxsy-ifYCOHHXiH-bXN41B4nFvEq5-R-U
