### Create Offer (Text Offer)
POST http://localhost:3000/api/offer/createOffer HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6IkNyZWF0b3IiLCJsYXN0TmFtZSI6IlRlc3QiLCJkaXNwbGF5TmFtZSI6IkNyZWF0b3JUZXN0IiwiZW1haWwiOiJjcmVhdG9yQGdtYWlsLmNvbSIsInJvbGUiOiJjcmVhdG9yIiwiYXZhdGFyIjoiYW5vbi5wbmciLCJiYWxhbmNlIjoiMCIsInJhdGluZyI6MCwiaWF0IjoxNzI2MDU2MjkyLCJleHAiOjE3MjYwNTk4OTJ9.sXvjoAIiDqxBXkDqB88ozzVkd46oFPJhS3VQWaQyy-A

{
  "contestId": 1,
  "contestType": "text",
  "offerData": "This is a text offer."
}

### Reject Offer
POST http://localhost:3000/api/offer/setOfferStatus HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkN1c3RvbWVyIiwibGFzdE5hbWUiOiJUZXN0IiwiZGlzcGxheU5hbWUiOiJDdXN0b21lclRlc3QiLCJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImF2YXRhciI6ImFub24ucG5nIiwiYmFsYW5jZSI6IjAiLCJyYXRpbmciOjAsImlhdCI6MTcyNjA1NjQwNSwiZXhwIjoxNzI2MDYwMDA1fQ.5MYK0YGvdsByGYbuJAkkwEbdh3UoOwjFcU2hkZsgQ9g

{
  "command": "reject",
  "offerId": 1,
  "creatorId": 2,
  "contestId": 1
}

### Resolve Offer
POST http://localhost:3000/api/offer/setOfferStatus HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkN1c3RvbWVyIiwibGFzdE5hbWUiOiJUZXN0IiwiZGlzcGxheU5hbWUiOiJDdXN0b21lclRlc3QiLCJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImF2YXRhciI6ImFub24ucG5nIiwiYmFsYW5jZSI6IjAiLCJyYXRpbmciOjAsImlhdCI6MTcyNjA1NjQwNSwiZXhwIjoxNzI2MDYwMDA1fQ.5MYK0YGvdsByGYbuJAkkwEbdh3UoOwjFcU2hkZsgQ9g

{
  "command": "resolve",
  "offerId": 2,
  "creatorId": 2,
  "contestId": 1,
  "orderId": "fdd026c3-f440-412c-849b-e18d6f2aba1a",
  "priority": 1
}
