### Payment
POST http://localhost:3000/api/payment/pay HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkN1c3RvbWVyIiwibGFzdE5hbWUiOiJUZXN0IiwiZGlzcGxheU5hbWUiOiJDdXN0b21lclRlc3QiLCJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImF2YXRhciI6ImFub24ucG5nIiwiYmFsYW5jZSI6IjAiLCJyYXRpbmciOjAsImlhdCI6MTcyNTgzOTc1MCwiZXhwIjoxNzI1ODQzMzUwfQ.StV7ownbs_5pwdV1vxVjUwoAEoJWAI2awlGUNV5lWG8

{
  "name": "Yriy",
  "number": "4111 1111 1111 1111",
  "cvc": "505",
  "expiry": "09/26",
  "price": 100,
  "contests": [
    {
      "contestType": "name",
      "title": "Contest 1",
      "industry": "Tech",
      "focusOfWork": "Development of new tech products",
      "targetCustomer": "Tech enthusiasts",
      "styleName": "Modern",
      "nameVenture": "Tech Ventures"
    },
    {
      "contestType": "logo",
      "title": "Contest 2",
      "industry": "Health",
      "focusOfWork": "Health and wellness",
      "targetCustomer": "Health-conscious individuals",
      "brandStyle": "Clean and modern"
    }
  ]
}

### Cash out
POST http://localhost:3000/api/payment/cashout HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkN1c3RvbWVyIiwibGFzdE5hbWUiOiJUZXN0IiwiZGlzcGxheU5hbWUiOiJDdXN0b21lclRlc3QiLCJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImF2YXRhciI6ImFub24ucG5nIiwiYmFsYW5jZSI6IjAiLCJyYXRpbmciOjAsImlhdCI6MTcyNTgzOTc1MCwiZXhwIjoxNzI1ODQzMzUwfQ.StV7ownbs_5pwdV1vxVjUwoAEoJWAI2awlGUNV5lWG8

{
  "name": "Yriy",
  "number": "4111 1111 1111 1111",
  "cvc": "505",
  "expiry": "09/26",
  "sum": 50
}
