### Payment & create contests
POST http://localhost:3000/api/payment/pay HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkN1c3RvbWVyIiwibGFzdE5hbWUiOiJUZXN0IiwiZGlzcGxheU5hbWUiOiJDdXN0b21lclRlc3QiLCJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImF2YXRhciI6ImFub24ucG5nIiwiYmFsYW5jZSI6IjAiLCJyYXRpbmciOjAsImlhdCI6MTcyNjA1NjE0NywiZXhwIjoxNzI2MDU5NzQ3fQ.Lvq9D5BmtXpBXHjYDz-JQ1yILRCBW1UkdwCO52ezDsA

{
  "name": "Yriy",
  "number": "4111 1111 1111 1111",
  "cvc": "505",
  "expiry": "09/26",
  "price": 100,
  "contests": [
    {
      "contestType": "name",
      "title": "Contest 1",
      "industry": "Tech",
      "focusOfWork": "Development of new tech products",
      "targetCustomer": "Tech enthusiasts",
      "styleName": "Modern",
      "nameVenture": "Tech Ventures"
    },
    {
      "contestType": "logo",
      "title": "Contest 2",
      "industry": "Health",
      "focusOfWork": "Health and wellness",
      "targetCustomer": "Health-conscious individuals",
      "brandStyle": "Clean and modern"
    },
    {
      "contestType": "tagline",
      "title": "Contest 3",
      "industry": "Marketing",
      "focusOfWork": "Brand promotion",
      "targetCustomer": "Businesses"
    }
  ]
}

// =============================================

### Cash out
POST http://localhost:3000/api/payment/cashout HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkN1c3RvbWVyIiwibGFzdE5hbWUiOiJUZXN0IiwiZGlzcGxheU5hbWUiOiJDdXN0b21lclRlc3QiLCJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImF2YXRhciI6ImFub24ucG5nIiwiYmFsYW5jZSI6IjAiLCJyYXRpbmciOjAsImlhdCI6MTcyNjAwNTI5NSwiZXhwIjoxNzI2MDA4ODk1fQ.DS4Y9hWhON8AxxjoamPgaAv3lCmVKf9hPRHbTIWtJcM

{
  "name": "Yriy",
  "number": "4111 1111 1111 1111",
  "cvc": "505",
  "expiry": "09/26",
  "sum": 50
}
