### Get User
GET http://localhost:3000/api/user/getUser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkN1c3RvbWVyIiwibGFzdE5hbWUiOiJUZXN0IiwiZGlzcGxheU5hbWUiOiJDdXN0b21lclRlc3QiLCJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImF2YXRhciI6ImFub24ucG5nIiwiYmFsYW5jZSI6IjAiLCJyYXRpbmciOjAsImlhdCI6MTcyNTgzOTc1MCwiZXhwIjoxNzI1ODQzMzUwfQ.StV7ownbs_5pwdV1vxVjUwoAEoJWAI2awlGUNV5lWG8
Content-Type: application/json

### Update user
PATCH http://localhost:3000/api/user/updateUser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkN1c3RvbWVyIiwibGFzdE5hbWUiOiJUZXN0IiwiZGlzcGxheU5hbWUiOiJDdXN0b21lclRlc3QiLCJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImF2YXRhciI6ImFub24ucG5nIiwiYmFsYW5jZSI6IjAiLCJyYXRpbmciOjAsImlhdCI6MTcyNTgzOTc1MCwiZXhwIjoxNzI1ODQzMzUwfQ.StV7ownbs_5pwdV1vxVjUwoAEoJWAI2awlGUNV5lWG8
Content-Type: application/json

{
  "firstName": "UpdatedFirstName",
  "lastName": "UpdatedLastName",
  "displayName": "UpdatedDisplayName",
  "email": "updatedemail52@gmail.com",
  "role": "customer"
}

### Change Mark !!!!!!!!!!!!!!!!!!!!
PATCH http://localhost:3000/api/user/changeMark HTTP/1.1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkN1c3RvbWVyIiwibGFzdE5hbWUiOiJUZXN0IiwiZGlzcGxheU5hbWUiOiJDdXN0b21lclRlc3QiLCJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImF2YXRhciI6ImFub24ucG5nIiwiYmFsYW5jZSI6IjAiLCJyYXRpbmciOjAsImlhdCI6MTcyNTgzOTc1MCwiZXhwIjoxNzI1ODQzMzUwfQ.StV7ownbs_5pwdV1vxVjUwoAEoJWAI2awlGUNV5lWG8
Content-Type: application/json

{
  "isFirst": true,
  "offerId": 123,
  "creatorId": 456,
  "mark": 4.5
}
