### Get current user
GET http://localhost:3000/api/user/getCurrentUser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6IkNyZWF0b3IiLCJsYXN0TmFtZSI6IlRlc3QiLCJkaXNwbGF5TmFtZSI6IkNyZWF0b3JUZXN0IiwiZW1haWwiOiJjcmVhdG9yQGdtYWlsLmNvbSIsInJvbGUiOiJjcmVhdG9yIiwiYXZhdGFyIjoiYW5vbi5wbmciLCJiYWxhbmNlIjoiMCIsInJhdGluZyI6MCwiaWF0IjoxNzI2MDUxODQ3LCJleHAiOjE3MjYwNTU0NDd9.veqeficoh0MHKDTcoJms5_R1j9cTqz9bzdhEuXTyLlc
Content-Type: application/json

### Update user
PATCH http://localhost:3000/api/user/updateUser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6IkNyZWF0b3IiLCJsYXN0TmFtZSI6IlRlc3QiLCJkaXNwbGF5TmFtZSI6IkNyZWF0b3JUZXN0IiwiZW1haWwiOiJjcmVhdG9yQGdtYWlsLmNvbSIsInJvbGUiOiJjcmVhdG9yIiwiYXZhdGFyIjoiYW5vbi5wbmciLCJiYWxhbmNlIjoiMCIsInJhdGluZyI6MCwiaWF0IjoxNzI2MDUxODQ3LCJleHAiOjE3MjYwNTU0NDd9.veqeficoh0MHKDTcoJms5_R1j9cTqz9bzdhEuXTyLlc
Content-Type: application/json

{
  "firstName": "UpdatedFirstName",
  "lastName": "UpdatedLastName",
  "displayName": "UpdatedDisplayName",
  "email": "updatedemail52@gmail.com",
  "role": "customer"
}

### Change Mark !!!!!!!!!!!!!!!!!!!!
PATCH http://localhost:3000/api/user/changeMark HTTP/1.1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkN1c3RvbWVyIiwibGFzdE5hbWUiOiJUZXN0IiwiZGlzcGxheU5hbWUiOiJDdXN0b21lclRlc3QiLCJlbWFpbCI6ImN1c3RvbWVyQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImF2YXRhciI6ImFub24ucG5nIiwiYmFsYW5jZSI6IjAiLCJyYXRpbmciOjAsImlhdCI6MTcyNjA1MjAxMiwiZXhwIjoxNzI2MDU1NjEyfQ.2iFxWKxrDy6tx3_4RvNhPc8JahLb62WigeOmVdcBMMs
Content-Type: application/json

{
  "isFirst": true,
  "offerId": 1,
  "creatorId": 1,
  "mark": 4.5
}
